### PR TITLE
Content layouts

### PR DESCRIPTION
**Pull request by suejinkim20**

### CODE REVIEW

**Comment by mbwatson** [comment]
i'm getting a ReferenceError complaining about the CardMedia component from within the PanelMenu component. i also see a couple browser warnings in the console that we should clear up before merging.

**Review by mbwatson — CHANGES_REQUESTED** [review]
i'm getting a ReferenceError complaining about the CardMedia component from within the PanelMenu component. i also see a couple browser warnings in the console that we should clear up before merging.

**Comment by suejinkim20** [comment]
Note: Browser warning indicates that classNames do not match. This seems to be a recurring issue between MUI and Next.js. Need to refer to the following links for more info and potential updates:
- https://githubmemory.com/repo/mui-org/material-ui/issues/27512
- https://github.com/mui-org/material-ui/pull/27088#issuecomment-885278495
- https://github.com/mui-org/material-ui/issues/7836

**Comment by suejinkim20** [comment]
Yes! ReferenceError for CardMedia is fixed and I made a note about the browser warning with the reference links

> i'm getting a ReferenceError complaining about the CardMedia component from within the PanelMenu component. i also see a couple browser warnings in the console that we should clear up before merging.

**Pull request merged**
